### ISSUE TITLE
Embedding options

### ISSUE THREAD

**Issue by nelsonmau** [Dataninja/advanced-mapping-tool#44]
Possibilità di abilitare la pubblicazione del logo solo in modalità ?embed
Includere nel conf in // Embed options la funzionalità di logo active: true/false

**Comment by jenkin** [comment]
C'è forse un modo più semplice per gestire questa eventualità con semplice css:

``` css
body .logo {
    display: none;
}   

body.embed .logo {
    display: inline-block;
}
```

Avendo naturalmente attivato il logo nella configurazione. In generale al body della mappa vengono associate delle classi omonime per le varie modalità di visualizzazione (embed, widget, ecc.). Quindi si possono sovrascrivere comodamente le regole css standard preponendo body.[modalità] al selettore.
